CARE_AND_TREATMENT = 'YKs1kXOLb0u'

SAT = 'grpiGkcSlNN'

PTV = 'BgTTypHIWom'

PTV_STAGE = 'i51KpB0xe7s'

TB = 'eewA8qgQWbX'

TB_STAGE = 'I7kaPiAU7zH'

DPI = 'JcDCTqrr5wK'

DPI_STAGE = 'lh2T9PCnMfR'

INDEX = 'h5ZjECdvShC'

INDEX_DETAILS_STAGE = 'loAZMSYmT4e'

INDEX_CONTACTS_STAGE = 'TOImEk5U0dw'